### ISSUE TITLE
lsm303ah: wrong register used in lsm303ah_xl_fifo_data_level_get() function

### ISSUE THREAD

**Issue by vadim-bey** [STMicroelectronics/lsm303ah-pid#1]
### Device part numbers

lsm303ah

### Type of bug

driver - lsm303ah_STdC/driver/lsm303ah_reg.c

### Describe the bug

function lsm303ah_xl_fifo_data_level_get() uses a wrong register to read the second part of available samples' count. Also DIFF[8] is shifted incorrectly.

From the datasheet:
FIFO_SAMPLES_A register description
DIFF [7:0]

Concatenated with DIFF8 bit in FIFO_SRC_A (2Fh) register, it represents the
number of unread samples stored in FIFO. (000000000 = FIFO empty;
100000000 = FIFO full, 256 unread samples).

### Additional context

Proposed patch:

diff --git a/lsm303ah_STdC/driver/lsm303ah_reg.c b/lsm303ah_STdC/driver/lsm303ah_reg.c
index e0a1168..a844ea1 100644
--- a/lsm303ah_STdC/driver/lsm303ah_reg.c
+++ b/lsm303ah_STdC/driver/lsm303ah_reg.c
@@ -3348,11 +3348,11 @@ int32_t lsm303ah_xl_fifo_data_level_get(stmdev_ctx_t *ctx, uint16_t *val)
   int32_t ret;
 
   ret = lsm303ah_read_reg(ctx, LSM303AH_FIFO_SRC_A, (uint8_t*)&fifo_src_a, 1);
-  if(ret == 0){
-    ret = lsm303ah_read_reg(ctx, LSM303AH_FIFO_SRC_A, &fifo_sample_a, 1);
+  if(ret == 0) {
+    ret = lsm303ah_read_reg(ctx, LSM303AH_FIFO_SAMPLES_A, &fifo_sample_a, 1);
     *val = fifo_src_a.diff;
-    *val = *val << 7;
-    *val += fifo_sample_a;
+    *val = *val << 8;
+    *val |= fifo_sample_a;
   }
   return ret;
 }

**Comment by avisconti** [comment]
@vadim-bey 
Yes, the routine is bugged, thanks for pointing out.

If you agree you can submit a PR addressing this bug and I'll review and accept it. In alternative I can do the patch.
Thanks!

**Comment by vadim-bey** [comment]
I trust you on creating this PR, please fix it, thanks :)

**Comment by avisconti** [comment]
@vadim-bey 
I transferred the issue over the correct repo, which is this one.

**Comment by avisconti** [comment]
@vadim-bey 
I'm going to commit, but, before, please take a look and if you can try it would be great!
 
```
  int32_t lsm303ah_xl_fifo_data_level_get(stmdev_ctx_t *ctx,
                                          uint16_t *val)
  {
    lsm303ah_fifo_src_a_t fifo_src_a;
    uint8_t fifo_sample_a;
    int32_t ret;

    ret = lsm303ah_read_reg(ctx, LSM303AH_FIFO_SRC_A, (uint8_t *)&fifo_src_a, 1);

    if (ret == 0)
    {
      ret = lsm303ah_read_reg(ctx, LSM303AH_FIFO_SAMPLES_A, &fifo_sample_a, 1);
      *val = fifo_src_a.diff;
      *val = *val << 8;
      *val += fifo_sample_a;
    }

    return ret;
  }
```

**Comment by avisconti** [comment]
This one is even better
```
int32_t lsm303ah_xl_fifo_data_level_get(stmdev_ctx_t *ctx,
                                          uint16_t *val)
  {
    lsm303ah_fifo_src_a_t fifo_src_a;
    uint8_t fifo_sample_a;
    int32_t ret;

    ret = lsm303ah_read_reg(ctx, LSM303AH_FIFO_SRC_A, (uint8_t *)&fifo_src_a, 1);

    if (ret == 0)
    {
      ret = lsm303ah_read_reg(ctx, LSM303AH_FIFO_SAMPLES_A, &fifo_sample_a, 1);
      *val = (fifo_src_a.diff << 8) + fifo_sample_a;
    }

    return ret;
  }
```

**Comment by vadim-bey** [comment]
Well I did test the patch I attached to the description originally - and it seemed to be working.
Now I am not so sure about this latest variant, since fifo_src_a.diff is defined as a 1 bit bitfield, so shifting might not work as expected.

**Comment by avisconti** [comment]
> Well I did test the patch I attached to the description originally - and it seemed to be working. Now I am not so sure about this latest variant, since fifo_src_a.diff is defined as a 1 bit bitfield, so shifting might not work as expected.

Yes, I think that it should work but maybe not always. Moreover it might not be MISRA compliant.
So, I'll go with my first one implementation (sorry, but it's difficult to read your implementation. You should try to use ``` before and after the code to see it better in this markdown page, or provide a PR)

**Comment by avisconti** [comment]
I'm closing issue down, but you can re-open it in case something is wrong.
Thanks again!

**Comment by vadim-bey** [comment]
Excuse me, but when is this fix going to be synced with the main STMicroelectronics repo that I originally created this issue for ?

**Comment by avisconti** [comment]
> Excuse me, but when is this fix going to be synced with the main STMicroelectronics repo that I originally created this issue for ?

Did it now... sorry!

**Comment by vadim-bey** [comment]
I still see the old code in STMicroelectronics/STMems_Standard_C_drivers ... also I see commit message saying it is "Splitted from](https://github.com/STMicroelectronics/lsm303ah/commit/f1ea048b569fe169e1092206556e4dbd6bd3c407) [https://github.com/STMicroelectronics/STMems_Standard](https://github.com/STMicroelectronics/STMems_Standard_C_drivers)

**Comment by avisconti** [comment]
You should see:

```
$ git log --oneline
0e80d91 STdC submodules: Aligned to latest lsm303ah driver
28cef4c lsm6dsrx examples: add FSM freefall detection
7e6970c lsm6dsrx examples: add MLC sixd position
acff841 ism330dhcx examples: add FSM freefall detection
74029f2 ism330dhcx examples: add MLC sixd position
e26c136 iis2iclx examples: add MLC tilt angle calculation
56665be iis2iclx examples: add FSM tilt monitoring
2212b3d STdC submodules: alignment to latest status
```
